### PR TITLE
travis CI test for ipynb files

### PR DESCRIPTION
**Pull request by haraldschilly**
Earlier today we noticed that some ipynb files were corrupt. Then, they don't work and it's confusing. This is a simple continuous integration test validating the ipynb files.

Confused? Well, it's easy. To get you started with this, simply goto https://travis-ci.org and use your github account. Then activate your `rbeezer/sla` repository there, it's a toggle button. That's all.

In the end, you will see build results like this one: https://travis-ci.org/haraldschilly/sla and when this test fails, you'll get emails... It even tells you about problems in pull requests before a merge :boom:

### CODE REVIEW

**Comment by rbeezer** [comment]
Thanks very much, Harald!  I'll get this sorted once JMM winds down.

**Comment by rbeezer** [comment]
Thanks very much, Harald, for getting this all together, and for the instructions!  I think everything is in place, but I have nothing else to push right now to test.  ;-)  Now I have a good model for doing this on other projects.

I fetch and then merge locally with a rebase and edits to the history.  So just trash your branch on your end.

I'll be exploring the Library and share server in the next couple of days.

**Comment by haraldschilly** [comment]
Good, glad it's helpful

> but I have nothing else to push right now to test. ;-)

yes, well, you can try to purposely breaking it in a branch. 

Here is an other example where you can see status information for each branch: https://travis-ci.org/sagemath/sage_sample/branches So, that's how it could look once all this testing is working as it should.

**Comment by rbeezer** [comment]
Thanks again, Harald.  I got the right kernelspec in place (`sagemath`), so did push some changes just after my last comment, and so can see the summary now.

**AND** I put a badge into my README. ;-)

Maybe I'll put the `*.tex` versions in place and run `pdflatex` on them.  Along with the JSON validation, that'd do a pretty good job of verifying nothing too nasty was broken.

Thanks for the education.

**Pull request closed without merging**
